version: '3.7'
services:
  php:
    build: ./docker/php
    volumes:
      - ./:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    environment:
      PHP_IDE_CONFIG: "serverName=run_rabit"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    working_dir: /app
    ports:
      - '8000:80'
    links:
      - rabbitmq
    depends_on:
      - db
      - redis
    networks:
      - rabbitmq_net
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - rabbitmq_net
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - rabbitmq_net
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
  redis:
    image: redis:3.0
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 6379:6379
    networks:
      - rabbitmq_net
volumes:
  rabbitmq_data:
  rabbitmq_log:
  redis_data:
    driver: local

networks:
  rabbitmq_net:
    driver: bridge