<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "news".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property string $aliasModel
 */
abstract class News extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'title' => Yii::t('models', 'Title'),
            'content' => Yii::t('models', 'Content'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\NewsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\NewsQuery(get_called_class());
    }


}
